export const brands = [
  // "Gucci",
  // "Louis Vuitton",
  // "Balenciaga",
  // "Prada",
  // "Chanel",
  // "Supreme",
  // "Off-White",
  // "Fear of God",
  // "Puma",
  // "A Bathing Ape",
  // "Zara",
  // "H&M",
  // "Uniqlo",
  // "Levi’s",
  // "Nike",
  // "Adidas",

  "Levi’s",
  "Nike",
  "Adidas",
  "Zara",
  "H&M",
  "Forever 21",
  "Shein",
  "American Eagle Outfitters",
  "Polo Ralph Lauren",
  "Gap",
  "Urban Outfitters",
  "Topshop",
  "Converse",
  "Dr. Martens",
  "Uniqlo",
  "Patagonia",
  "The North Face",
  "Columbia Sportswear",
  "Champion",
  "ASOS",
];
